services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Console (web UI)
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data

  minio-fastapi-relay:
    container_name: minio-fastapi-relay
    restart: unless-stopped
    build: .
    depends_on:
      - minio
      - db
    ports:
      - "8000:8000"
    environment:
      MINIO_ENDPOINT: minio:9000 # Change this to your ip or domain to access the download url
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_RELAY_BUCKET_NAME: miniorelay

  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    # ports:
    #   - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: minio_relay
      POSTGRES_PASSWORD: postgres

  # adminer:
  #   image: adminer
  #   restart: unless-stopped
  #   ports:
  #     - "8080:8080"
