version: 1
formatters:
  colored:
    (): uvicorn.logging.DefaultFormatter
    format: '%(asctime)s | %(levelprefix)s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  default:
    class: logging.StreamHandler
    formatter: colored
    stream: ext://sys.stdout

loggers:
  uvicorn:
    handlers: [default]
    level: INFO

  uvicorn.error:
    handlers: [default]
    level: INFO
    propagate: False

  uvicorn.access:
    handlers: [default]
    level: INFO
    propagate: False

root:
  handlers: [default]
  level: INFO
